### ISSUE TITLE
Provide a direct link to prepared netflix dataset

### ISSUE THREAD

**Issue by cwpearson** [wei-tan/CuMF#11]
The readme provides this link:

https://ibm.box.com/s/5vmh77up8reodvihiq0ri66jltg9h4uh

Unforunately, it is difficult to fetch this data without invoking a web browser. Can you provide a direct link to the file that would be suitable to pass to `wget` or `curl`, for example?

Thanks!

**Comment by wei-tan** [comment]
Hi Carl, here you are: https://ibm.box.com/shared/static/5vmh77up8reodvihiq0ri66jltg9h4uh.tar
