### ISSUE TITLE
Does CuMF support implicit feedback data?

### ISSUE THREAD

**Issue by hangelwen** [wei-tan/CuMF#12]

**Comment by wei-tan** [comment]
Hi so far not. But it should not be difficult to add that, by changing the get_hermitian kernel. The solver kernel does not need to be changed.

**Comment by wei-tan** [comment]
@hangelwen 
please check the implicit branch for the first commit of implicit MF. I have checked the correctness by comparing with the result from https://github.com/benfred/implicit .
