### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by umezbhatia** [wei-tan/CuMF#16]
Hi, I tried creating the dataset as mentioned in prepare_netflix_data.py. 
However, the URL 'http://www.select.cs.cmu.edu/code/graphlab/datasets/ seems to be invalid. 
Could you please let me know a workaround?

**Comment by dlunga** [comment]
Download one from the link provided in the README.

**Comment by wei-tan** [comment]
Yes you can also use the link from README. Thank you @dlunga!

**Comment by Zialus** [comment]
The [link](https://ibm.ent.box.com/shared/static/5vmh77up8reodvihiq0ri66jltg9h4uh.tar) in the README isn't working either.

Is there any alternative?

**Comment by wei-tan** [comment]
I just updated the link in README. Thx for pointing it out.
