### ISSUE TITLE
Extracting Outputs

### ISSUE THREAD

**Issue by dlunga** [wei-tan/CuMF#17]
How and where do I extract  `X` and `Theta` after convergence? Are these being written to a file on the host device?

**Comment by wei-tan** [comment]
in https://github.com/cuMF/cumf_als/blob/master/als.cu

 `float doALS(const int* csrRowIndexHostPtr, const int* csrColIndexHostPtr, const float* csrValHostPtr,
		const int* cscRowIndexHostPtr, const int* cscColIndexHostPtr, const float* cscValHostPtr,
		const int* cooRowIndexHostPtr, float* thetaTHost, float* XTHost,
		const int * cooRowIndexTestHostPtr, const int * cooColIndexTestHostPtr, const float * cooValHostTestPtr,
		const int m, const int n, const int f, const long nnz, const long nnz_test, const float lambda,
		const int ITERS, const int X_BATCH, const int THETA_BATCH, const int DEVICEID)
`

You will see:
`	//copy feature vectors back to host
	cudacall(cudaMemcpy(thetaTHost, thetaT, (size_t ) (n * f * sizeof(thetaT[0])), cudaMemcpyDeviceToHost));
	cudacall(cudaMemcpy(XTHost, XT, (size_t ) (m * f * sizeof(XT[0])), cudaMemcpyDeviceToHost));
`

You should be able to manipulate x and Theta on host, e.g., writing to a file.
