### ISSUE TITLE
sgd?

### ISSUE THREAD

**Issue by chentingpc** [wei-tan/CuMF#3]
it runs very fast, great work! just wonder did you try sgd, how much can it be optimized?

**Comment by wei-tan** [comment]
Thanks! We are working on a SGD version. Please stay tuned :)

**Comment by chentingpc** [comment]
Great, Look forward to it! Also, it would be wonderful if it can be made as extensible kernels for broader families of models, such as word2vec, which is similar to matrix factorization but with different loss, essentially a triple based optimization.

**Comment by wei-tan** [comment]
Yeah... I do have a version that implements GloVe (http://nlp.stanford.edu/projects/glove/). For Word2Vec, wonder how easy it is to leverage MF. It would be more straightforward to use TensorFlow to implement it?

**Comment by chentingpc** [comment]
Tensorflow can do all, but it seems matrix factorization type of network (including Word2Vec) is not very fast, probably due to the lack of dense matrix-matrix operations which can be easily boosted. It seems their kernels are not specially optimized for sparse or vector based operations, I am not sure.

**Comment by wei-tan** [comment]
I have to take a look at TF code. Does it ever write its own CUDA kernels, or it solely rely on cuDNN, cuBLAS and cuSPARSE? As you can see from cuMF code, I had to write a few CUDA kernels to implement sparse MF.

**Comment by chentingpc** [comment]
I don't think so.. you may want to look at the following link in their tutorial which provide two versions of implementation: https://www.tensorflow.org/versions/r0.8/tutorials/word2vec/index.html#optimizing-the-implementation

**Comment by llcao** [comment]
I think TF does not have operators specified for sparse matrix. But Word2Vec is not based on sparse matrix multiplications, but dense ones. The sparse nature is only used implicitly during lock-free training. 

Mikolov's original Word2Vec implementation works in a lock-free manner. In contrast, TF's standard SGD is not as parallel as ALS, and does not use the lock-free property. That may be the reason why TF is slow in Word2Vec training.

**Comment by chentingpc** [comment]
tensorflow has embedding lookup operator that can be used for triple based problem (map user/item => score), which can be view as (sparse) matrix factorization problem if you treat user/word as row, item/context as col, and score as entry. So if you can do fast SGD for MF, I think it should be applied to word2vec (skip-gram).

BTW, here is a fast implementation of word2vec (cbow, not skip-gram) on GPU: https://github.com/ChenglongChen/word2vec_cbow

**Comment by wei-tan** [comment]
Please stay tuned, we have a SGD version to be released very soon...
