### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by isratnisa** [wei-tan/CuMF#5]
Hi,
We are trying to run your code on our machine as it is.
Our machine has a 16GB ram with free memory around 10GB.
Even then we are facing MemoryError in the following line:
train_j,train_i,train_rating = np.loadtxt(train_data_file,dtype=np.int32,skiprows=3,unpack=True)

Can you give us pointers on why and how we could be resolving this issue?
Thanks

**Comment by wei-tan** [comment]
The netflix data is several GB. You may need much more memory space because numpy requires that. Try the binary data we already pre-processed for you at here: https://ibm.box.com/s/5vmh77up8reodvihiq0ri66jltg9h4uh

**Comment by isratnisa** [comment]
Thank you.

**Comment by isratnisa** [comment]
Hi,
Sorry to bother you again. Just a quick question.  Can you please tell me
where can I find the actual dataset for Yahoo music? Your repository
doesn't seem like have one. I tried Yahoo website but got some weird
dataset.

Thank you for your time.

**Comment by wei-tan** [comment]
http://webscope.sandbox.yahoo.com/catalog.php?datatype=c
Please download the "C15 - Yahoo! Music user ratings of musical tracks, albums, artists and genres, v 1.0 (1.5 Gbyte)" and format it as instructed here: https://github.com/wei-tan/CuMF/blob/master/scripts/prepare_input.ipynb

**Comment by wei-tan** [comment]
@isratnisa: we have updated code and readme regarding input data. Take a look if you still want to try cuMF :-)

**Comment by isratnisa** [comment]
Of course. Thank you.
