### ISSUE TITLE
it cause 'core dump' on GTX950m(4G) with netflex data....

### ISSUE THREAD

**Issue by SeekPoint** [wei-tan/CuMF#7]
envy@ub1404:~/os_pri/github/CuMF$ tree
.
├── als.cu
├── als.h
├── als.o
├── host_utilities.cpp
├── host_utilities.h
├── host_utilities.o
├── images
│   ├── mf.png
│   └── spark-gpu.png
├── LICENSE
├── main
├── main.cu
├── main.o
├── Makefile
├── netflix_mme
├── netflix_mm.txt
├── print-test-result.sh
├── README.md
├── scripts
│   ├── prepare_input.ipynb
│   ├── R_test_coo.col.bin
│   ├── R_test_coo.data.bin
│   └── R_test_coo.row.bin
├── tensorflow
│   ├── als_tf.cc
│   ├── build_tf_op.sh
│   ├── cumf_as_tensorflow_ops_test.ipynb
│   └── cumf_as_tensorflow_ops_test.py
├── test_als.sh
└── yknote_build_debug_log

3 directories, 27 files
envy@ub1404:~/os_pri/github/CuMF$ 
envy@ub1404:~/os_pri/github/CuMF$ 
envy@ub1404:~/os_pri/github/CuMF$ ./main 100 0.058 3
F = 100, lambda = 0.058, THETA_BATCH = 3 
*******starting loading training and testing sets to host.

 loading COO...
Unable to open file!
 loading CSR...
Unable to open file!
 loading CSC...
Unable to open file!
 loading COO Row...
Segmentation fault (core dumped)
envy@ub1404:~/os_pri/github/CuMF$

**Comment by wei-tan** [comment]
Hi, have you looked at https://github.com/wei-tan/CuMF/blob/master/scripts/prepare_input.ipynb to prepare for the data files needed?

**Comment by wei-tan** [comment]
Hi @loveJasmine : we have updated code and readme regarding input data. Just for your information :)
